# Generated by Django 3.1 on 2021-01-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='posts',
            new_name='post',
        ),
    ]
